#! /usr/bin/env bash

IFS_bak=$IFS
IFS='
'

if [ -z $1 ]; then
    echo 変更したい名前を引数に指定してください
    exit 1
fi

count=1

for file in $(ls | sort -n)
do
    mv $file $1-$(printf %02d $count).${file##*.}
    count=$(($count+1))
done

IFS=$IFS_bak

